apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: hellonode
  replicas: 1
  template:
    metadata:
      labels:
        app: hellonode
    spec:
      containers:
      - name: hellonode
        image: ajdocker02/nithello:v3 # Update the version of nginx from 1.14.2 to 1.16.1
        ports:
        - containerPort: 8080
